### ISSUE TITLE
希望有的分区

### ISSUE THREAD

**Issue by 520Noir** [KUN1007/kun-galgame-nuxt3#10]
1.资源发布区（1）
2.自由讨论区（1）
3.问题、建议反馈区（鲲）
4.Galgame讨论区（1）
5.水贴区
6.新人报道区
7.求物区（参考kf）（这三个区1）
没必要像kf一样弄那么多分区
括号后的数字是我认为需要的管理人数
等以后人变多了再增加

**Comment by KUN1007** [comment]
fixed at 6121b114b592e5029882750b03366bd3226fc741
