### ISSUE TITLE
版规草稿

### ISSUE THREAD

**Issue by 520Noir** [KUN1007/kun-galgame-nuxt3#11]
总:
1.禁止辱骂他人
2.禁止打探他人私人信息（如具体地址、姓名、手机号等）
3.禁止讨论政治（可以讨论社会现象，但不允许对具体的guanyuan和zhengfu做出评价，发现有明确讨论政治的直接ban）
4.发布帖子要在对应的区域
5.禁止引流、冒充他人
6.发现有故意损害论坛的直接ban

管理员:
1.对成员进行处理时要说明理由
2.设置奖励额度（每天50萌萌点），惩罚额度不限（具体如何惩罚视情况而定，需要讨论）

**Comment by KUN1007** [comment]
fixed at 27dbba057d34b1e271dfea4a95af233b7deb9efb
