### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 520Noir** [KUN1007/kun-galgame-nuxt3#16]
![Screenshot_20240221_130408_com microsoft emmx](https://github.com/KUN1007/kun-galgame-nuxt3/assets/157918706/c5997609-37ba-4d44-b11b-7b27bec233e9)
![Screenshot_20240221_130401_com microsoft emmx](https://github.com/KUN1007/kun-galgame-nuxt3/assets/157918706/6f2f4153-2bdb-44a8-82eb-2a3c78da987a)
![Screenshot_20240221_130343_com microsoft emmx](https://github.com/KUN1007/kun-galgame-nuxt3/assets/157918706/b7bac1a3-36f6-4279-ae2e-d8002c903a31)
![Screenshot_20240221_130341_com microsoft emmx](https://github.com/KUN1007/kun-galgame-nuxt3/assets/157918706/205a83b8-3b0c-4b67-9861-958cb670b12e)
这个消息提示系统明显有问题
而且是两种不同的bug
一种是无信息但提示有
一种是有信息但不提示

**Comment by KUN1007** [comment]
非常感谢您的反馈
这似乎是一个令人容易产生疑惑的地方，并不是 BUG，之后我们会对消息功能进行优化
