### ISSUE TITLE
为登录/注册按钮添加高亮区分

### ISSUE THREAD

**Issue by yingcangyouren** [KUN1007/kun-galgame-nuxt3#3]
![Screenshot_2024-02-14-23-47-47-393_com android chrome-edit](https://github.com/KUN1007/kun-galgame-nuxt3/assets/118684194/f8217028-d2eb-4f41-b6d9-ee88549ce98d)

希望能为注册和登录按钮制作选中高亮的效果，以更好更美观的表示选中状态。

**Comment by KUN1007** [comment]
非常感谢您的反馈！
我们会在之后实现这个效果！

**Comment by KUN1007** [comment]
目前，我们已经将登录页面样式调整
![1](https://github.com/KUN1007/kun-galgame-nuxt3/assets/89312077/05f5a7cf-4c0c-426b-8bf0-890b45fe1b07)
