### ISSUE TITLE
Add a “Return” button in topic detail page.

### ISSUE THREAD

**Issue by CloudeaSoft** [KUN1007/kun-galgame-nuxt3#32]
My opinion: In the current version, in order to return to the [Topic Pool] page or other entries(such as [Topic Categories], hot list), users either have to press the browser's back button or renavigate from the Topbar, which may can be inconvenient for them.
![image](https://github.com/KUN1007/kun-galgame-nuxt3/assets/129159758/cd589609-8669-46e6-94c4-cae502ec744b)

This is just a suggestion, as clicking the browser's back button isn't particularly cumbersome. However, based on application grahpic interfaces, I believe it would be beneficial to include a dedicated back button for convenience.

**Comment by KUN1007** [comment]
Thanks for your feedback, we will add it soon.
