### ISSUE TITLE
[Suggestion] Split User Table into User and UserProfile

### ISSUE THREAD

**Issue by CloudeaSoft** [KUN1007/kun-galgame-nuxt3#36]
Description:

Currently, the user table combines authentication and profile data. For better scalability and maintainability, I suggest splitting it into two separate tables: user for authentication and userprofile for profile information.

Rationale:

Separation of Concerns: Clearer division between authentication and profile data.

Flexibility: Easier to modify profile fields without affecting authentication.

Scalability: Optimized database performance for frequent profile updates.

**Comment by KUN1007** [comment]
Thank you for your feedback.
But we currently do not have plans to include this feature, as MongoDB does not focus too much on data relationships. Perhaps in the future, as our service expands and the number of forum users increases to a certain extent, we will consider adding it.
