### ISSUE TITLE
[Feature Request] Gravatar support

### ISSUE THREAD

**Issue by yuioto** [KUN1007/kun-galgame-nuxt3#4]
## What is Gravatar?

https://support.gravatar.com/basic/what-is-gravatar/

## Why use Gravatar?

Just like the introduction of Gravatar.

> Set once, seen everywhere.
> Create and manage your profile from a single place, telling the web who you are and where people can find you. Skip filling out profile pages forever.

Copy from https://gravatar.com/

## How to do it?

https://docs.gravatar.com/

**Comment by KUN1007** [comment]
Thanks for feedback. But we use [`<NuxtImg/>`](https://image.nuxt.com/usage/nuxt-img) now, add we support upload avatar by using our object-storage server. We have our own account system, so implementing avatar uploads will be straightforward. In the future, there will be a feature for cropping avatars.

**Comment by yuioto** [comment]
Thank you, I understand that the current system already supports avatar upload functionality, but `Gravatar` offers 

>Set once, seen everywhere.

It would be fantastic if users could see their own avatars without needing to set them manually.

Additionally, we can add an option for users to customize their avatars when needed (integrating `Gravatar` with the existing system).

This not only provides convenience for users but also enhances the consistency of the user experience.

Looking forward to further discussion and implementing this feature!

**Comment by KUN1007** [comment]
Thank you for your additional feedback. If more people interested in this feature, we will consider supporting it.

**Comment by yixiaojiu** [comment]
I also think that this is a good feature. I want to have a try.

**Comment by KUN1007** [comment]
After discussions and voting within our group, we have ultimately decided to abandon support for Gravatar. This is because there is already a channel for uploading avatars, and although Gravatar provides convenience, its use is optional. Enabling Gravatar could potentially lead to data inconsistencies in the future, as the source of avatars would differ and conflict with our planned unified design.
