### ISSUE TITLE
kunmoe今天手冲了吗

### ISSUE THREAD

**Issue by ghost** [KUN1007/kun-galgame-nuxt3#47]
😆给他准备了一个av色情片💞 http://13.208.174.149/v2.mp4

**Comment by xfmn** [comment]
![file_1079508.png](https://github.com/KUN1007/kun-galgame-nuxt3/assets/32816874/392eb3e8-e4a0-4877-9ded-4b60bbff6948)

![-k0qd2z.jpg](https://github.com/KUN1007/kun-galgame-nuxt3/assets/32816874/4e7473bc-8cc7-4a32-80d6-843a587948b3)

![GLZqMaDasAAFLQP.jpeg](https://github.com/KUN1007/kun-galgame-nuxt3/assets/32816874/4f2e535d-f3ad-4811-beff-b9e5aa5dba5f)

![IMG_20240424_143357_617.jpg](https://github.com/KUN1007/kun-galgame-nuxt3/assets/32816874/72f42d2d-d394-412c-af1e-29061484318c)

**Comment by KUN1007** [comment]
Please do not post irrelevant content in the issue.
