### ISSUE TITLE
[improvement reqest] The language options in settings cannot be hidden by clicking inside

### ISSUE THREAD

**Issue by kingwingfly** [KUN1007/kun-galgame-nuxt3#49]
![Screenshot 2024-04-28 010036](https://github.com/KUN1007/kun-galgame-nuxt3/assets/38573173/97d34e8d-8976-44d6-8433-f90c2aa6273c)

I can pack up the options by click outside of option menu, however, if I click inside the red circle, it won't be hidden as expected.

**Comment by KUN1007** [comment]
Thank you very much for your feedback.
But this seems to be the expected outcome from our perspective. It was designed this way from the beginning, and if others raise similar concerns in the future, we will consider making changes.
Thx:)
