### ISSUE TITLE
[Feature Request] Do not allow scrollbars to appear on the page

### ISSUE THREAD

**Issue by yuioto** [KUN1007/kun-galgame-nuxt3#63]
The editor Milkdown already slides, so it doesn't make sense to make the whole page slide again.

However, at more extreme screen sizes, this may result in the editor not being used, and more testing is needed.

Consider adding a button to the side of the editor to make it selectable. Or testing to automatically apply different effects to different screen sizes.

The homepage has the same problem.

**Comment by KUN1007** [comment]
fixed at https://github.com/KUN1007/kun-galgame-nuxt3/commit/b78fda521ff1eb583117f6a3892af1934c07afea
