### ISSUE TITLE
编辑界面格式支持

### ISSUE THREAD

**Issue by Ashiroid** [KUN1007/kun-galgame-nuxt3#71]
1. 如果要引入网页LaTex格式支持的话，可否一并支持基本的html语法，类似于[obsidian](https://obsidian.md)那种编辑模式？
 2. 另外，可否提供解除文字链接的功能？在某些已经生成链接后的情况，继续码字会导致整句被合并至链接中，同时无法对原有md格式进行修改，只能删了重新写
   - 比如在编辑链接界面，若链接栏为空，则清除选中文本链接?

**Comment by KUN1007** [comment]
第一点，如果考虑到可迁移性的话，暂时不太可能实现
第二点在计划内
