### ISSUE TITLE
关于登录页

### ISSUE THREAD

**Issue by Huaji250** [KUN1007/kun-galgame-nuxt3#9]
登录和人机验证可以一体化，没必要多个按钮
我的想法是，去掉人机验证按钮，留下登录按钮，
点登录需要验证就弹窗，点完提交就登录，
不需要验证那就直接登录。

**Comment by Huaji250** [comment]
哦对了，还有回车登录建议也加上

**Comment by KUN1007** [comment]
非常感谢您的反馈
刚才我们已经按照您的提议更改了登录按钮，并在点击后进行人机验证，验证成功后会自动登录
